[project]
name = "digiqual"
dynamic = ["version"]
description = "Statistical Toolkit for Reliability Assessment in NDT"
authors = [
  {name = "Josh Tyler", email = "josh.tyler@bristol.ac.uk"}
]




readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]



license = "MIT"
license-files = ["LICEN[CS]E*"]


dependencies = [
    "matplotlib>=3.9.4",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
    "mkdocstrings>=0.30.1",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "scipy>=1.13.1",
]

[build-system]
requires = ["uv_build >= 0.9.26, <0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
